# Generated by Django 6.0 on 2025-12-19 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان القضية')),
                ('description', models.TextField(verbose_name='وصف القضية')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد التنفيذ'), ('closed', 'مغلقة')], default='new', max_length=20, verbose_name='حالة القضية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_cases', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyer_cases', to=settings.AUTH_USER_MODEL, verbose_name='المحامي')),
            ],
        ),
    ]
