# Generated by Django 6.0 on 2025-12-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, help_text='اختياري — مثال: ⚖️ 🏢 👨\u200d👩\u200d👧', max_length=50, verbose_name='الأيقونة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='صورة الكرت')),
                ('service_type', models.CharField(choices=[('case', 'نوع قضية'), ('service', 'خدمة قانونية')], max_length=20, verbose_name='التصنيف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'خدمة / قضية',
                'verbose_name_plural': 'الخدمات والقضايا',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'قضية', 'verbose_name_plural': 'القضايا'},
        ),
    ]
