# Generated by Django 6.0 on 2025-12-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_legalservice_alter_case_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalservice',
            options={'ordering': ['order'], 'verbose_name': 'خدمة قانونية / قضية', 'verbose_name_plural': 'الخدمات والقضايا'},
        ),
        migrations.RemoveField(
            model_name='legalservice',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='legalservice',
            name='icon',
            field=models.CharField(blank=True, help_text='مثال: ⚖️ 🏢 👨\u200d👩\u200d👧', max_length=20, verbose_name='الأيقونة'),
        ),
        migrations.AlterField(
            model_name='legalservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='legal_services/', verbose_name='صورة الكرت'),
        ),
        migrations.AlterField(
            model_name='legalservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='legalservice',
            name='service_type',
            field=models.CharField(choices=[('case', 'قضية'), ('service', 'خدمة قانونية')], max_length=20, verbose_name='التصنيف'),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
