# Generated by Django 6.0 on 2025-12-20 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_phone_number_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم القضية'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, choices=[('civil', 'مدنية'), ('criminal', 'جنائية'), ('commercial', 'تجارية'), ('family', 'أحوال شخصية'), ('labor', 'عمالية'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع القضية'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('new', 'جديدة'), ('under_review', 'قيد المراجعة'), ('in_progress', 'قيد المتابعة'), ('closed', 'مغلقة')], default='new', max_length=20, verbose_name='حالة القضية'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(verbose_name='وصف القضية'),
        ),
        migrations.AlterField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_cases', to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان الوطني'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/id_cards/', verbose_name='صورة الهوية'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='السجل المدني'),
        ),
    ]
