# Generated by Django 6.0 on 2025-12-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_case_case_number_case_case_type_case_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='lawyer_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المحامي'),
        ),
    ]
