# Generated by Django 6.0 on 2025-12-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_case_lawyer_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casereply',
            options={'ordering': ['created_at'], 'verbose_name': 'رد', 'verbose_name_plural': 'الردود'},
        ),
        migrations.AddField(
            model_name='casereply',
            name='is_visible_for_client',
            field=models.BooleanField(default=True, verbose_name='مرئي للعميل'),
        ),
    ]
