# Generated by Django 6.0 on 2025-12-21 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_casereply_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'مفعل'), ('pending_agreement', 'معلّق بانتظار الاتفاقية'), ('payment_pending', 'بانتظار الدفع')], default='active', max_length=30, verbose_name='حالة الحساب'),
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='رمز الوصول')),
                ('office_name', models.CharField(default='مكتب المحاماة والاستشارات القانونية', max_length=255, verbose_name='اسم المكتب')),
                ('office_logo', models.ImageField(blank=True, null=True, upload_to='agreements/logos/', verbose_name='شعار المكتب')),
                ('title', models.CharField(default='اتفاقية تقديم خدمات قانونية', max_length=255, verbose_name='عنوان الاتفاقية')),
                ('agreement_text', models.TextField(verbose_name='نص الاتفاقية')),
                ('accepted_checkbox', models.BooleanField(default=False, verbose_name='موافقة (مربع)')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='agreements/signatures/', verbose_name='صورة التوقيع')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوقيع')),
                ('payment_required', models.BooleanField(default=True, verbose_name='يتطلب دفع')),
                ('payment_status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('pending', 'بانتظار الدفع'), ('paid', 'تم الدفع')], default='not_started', max_length=30, verbose_name='حالة الدفع')),
                ('status', models.CharField(choices=[('sent', 'مرسلة'), ('accepted', 'تمت الموافقة'), ('signed', 'تم التوقيع'), ('payment_pending', 'بانتظار الدفع'), ('paid', 'تم الدفع'), ('expired', 'منتهية')], default='sent', max_length=30, verbose_name='حالة الاتفاقية')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اتفاقية',
                'verbose_name_plural': 'الاتفاقيات',
                'ordering': ['-created_at'],
            },
        ),
    ]
