# Generated by Django 6.0 on 2025-12-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_account_status_useragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragreement',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ الدفع'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='رقم الإيصال'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='إيصال الدفع PDF'),
        ),
    ]
