# Generated by Django 6.0 on 2025-12-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_useragreement_paid_at_useragreement_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragreement',
            name='sadad_bill_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='رقم فاتورة سداد'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='sadad_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء سداد'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='sadad_status',
            field=models.CharField(choices=[('not_created', 'لم تُنشأ'), ('pending', 'بانتظار السداد'), ('paid', 'مدفوعة'), ('expired', 'منتهية')], default='not_created', max_length=20, verbose_name='حالة سداد'),
        ),
    ]
