# Generated by Django 6.0 on 2025-12-22 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useragreement_sadad_bill_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الاتفاقية')),
                ('agreement_text', models.TextField(verbose_name='نص الاتفاقية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'قالب اتفاقية',
                'verbose_name_plural': 'قوالب الاتفاقيات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='useragreement',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_agreements', to='accounts.agreementtemplate', verbose_name='قالب الاتفاقية'),
        ),
    ]
