# Generated by Django 6.0 on 2025-12-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_agreementtemplate_useragreement_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragreement',
            name='office_invoice_number',
            field=models.CharField(blank=True, help_text='ضع رقم الفاتورة الثابت للمكتب هنا (سيظهر للعميل).', max_length=32, null=True, verbose_name='رقم الفاتورة الموحد'),
        ),
        migrations.AlterField(
            model_name='useragreement',
            name='sadad_bill_number',
            field=models.CharField(blank=True, help_text='إذا كان رقم سداد ثابت للمكتب اتركه هنا (يتكرر لجميع العملاء).', max_length=32, null=True, verbose_name='رقم فاتورة سداد'),
        ),
    ]
