# Generated by Django 6.0 on 2025-12-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_useragreement_office_invoice_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useragreement',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='useragreement',
            name='client_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إدخال الإيصال من العميل'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='client_payment_receipt',
            field=models.CharField(blank=True, help_text='العميل يدخل رقم الإيصال بعد السداد/التحويل.', max_length=64, null=True, verbose_name='رقم إيصال العميل'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='payment_method',
            field=models.CharField(choices=[('sadad', 'سداد (من تطبيق البنك)'), ('bank_transfer', 'تحويل بنكي'), ('cash', 'يدوي/نقدي')], default='sadad', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'مفعل'), ('pending_agreement', 'معلّق بانتظار الاتفاقية'), ('payment_pending', 'بانتظار الدفع/المراجعة')], default='active', max_length=30, verbose_name='حالة الحساب'),
        ),
        migrations.AlterField(
            model_name='useragreement',
            name='office_invoice_number',
            field=models.CharField(blank=True, help_text='رقم ثابت تضعه من الأدمن ليظهر للعميل أثناء السداد.', max_length=64, null=True, verbose_name='رقم الفاتورة (ثابت للمكتب)'),
        ),
        migrations.AlterField(
            model_name='useragreement',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اعتماد الدفع'),
        ),
        migrations.AlterField(
            model_name='useragreement',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='يولده المكتب بعد الاعتماد (اختياري).', max_length=64, null=True, verbose_name='رقم إيصال المكتب'),
        ),
        migrations.AlterField(
            model_name='useragreement',
            name='sadad_bill_number',
            field=models.CharField(blank=True, help_text='إن كنت تستخدم رقم سداد ثابت، اتركه هنا (لا يوجد منع تكرار).', max_length=32, null=True, verbose_name='رقم فاتورة سداد (مرجعي)'),
        ),
        migrations.AlterField(
            model_name='useragreement',
            name='status',
            field=models.CharField(choices=[('sent', 'مرسلة'), ('accepted', 'تمت الموافقة'), ('signed', 'تم التوقيع'), ('payment_pending', 'بانتظار الدفع/إرسال الإيصال'), ('under_review', 'بانتظار مراجعة المكتب'), ('paid', 'تم الدفع'), ('rejected', 'مرفوض'), ('expired', 'منتهية')], default='sent', max_length=30, verbose_name='حالة الاتفاقية'),
        ),
    ]
