# Generated by Django 6.0 on 2025-12-22 10:09

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_useragreement_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragreement',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='accounts.case', verbose_name='القضية المرتبطة'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='client_receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_client_receipt_image, verbose_name='صورة إيصال العميل'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='client_receipt_image_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ رفع صورة الإيصال'),
        ),
    ]
