# Generated by Django 6.0 on 2025-12-24 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_useragreement_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragreement',
            name='accepted_checkbox',
            field=models.BooleanField(default=False, verbose_name='موافقة'),
        ),
        migrations.AlterField(
            model_name='useragreement',
            name='client_payment_receipt',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='رقم إيصال العميل'),
        ),
        migrations.AlterField(
            model_name='useragreement',
            name='office_invoice_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='رقم الفاتورة (ثابت للمكتب)'),
        ),
        migrations.AlterField(
            model_name='useragreement',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='رقم إيصال المكتب'),
        ),
        migrations.AlterField(
            model_name='useragreement',
            name='sadad_bill_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='رقم فاتورة سداد (مرجعي)'),
        ),
        migrations.CreateModel(
            name='ClientMasterFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='السجل المدني')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات داخلية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_folder', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'مجلد ماستر عميل',
                'verbose_name_plural': 'مجلدات الماستر للعملاء',
            },
        ),
        migrations.CreateModel(
            name='ClientMasterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='اسم المستند')),
                ('file', models.FileField(upload_to='clients/master_documents/', verbose_name='الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.clientmasterfolder', verbose_name='مجلد العميل')),
            ],
            options={
                'verbose_name': 'مستند ماستر',
                'verbose_name_plural': 'مستندات الماستر',
            },
        ),
        migrations.CreateModel(
            name='ClientMasterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('client', 'من العميل'), ('lawyer', 'من المحامي')], max_length=10, verbose_name='الاتجاه')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.clientmasterfolder', verbose_name='مجلد العميل')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة ماستر',
                'verbose_name_plural': 'رسائل الماستر',
                'ordering': ['-created_at'],
            },
        ),
    ]
