# Generated by Django 5.2.4 on 2026-01-05 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_useragreement_accepted_checkbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'تسجيل جديد'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('create_case', 'رفع قضية'), ('create_case_ops', 'رفع قضية (operations)'), ('upload_document', 'رفع مستند'), ('agreement_status', 'تغيير حالة اتفاقية'), ('payment_submit', 'إرسال إيصال دفع'), ('master_access', 'دخول الماستر'), ('master_send_message', 'إرسال رسالة من الماستر'), ('view', 'عرض صفحة'), ('other', 'أخرى')], default='other', max_length=50, verbose_name='الحدث')),
                ('message', models.CharField(blank=True, default='', max_length=255, verbose_name='وصف')),
                ('ip_address', models.CharField(blank=True, default='', max_length=64, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الحدث')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حدث مراقبة',
                'verbose_name_plural': 'سجل الأحداث',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('won', 'كسب'), ('lost', 'خسارة'), ('appeal', 'استئناف'), ('pending', 'بانتظار الحكم')], default='pending', max_length=20, verbose_name='النتيجة')),
                ('judgment_text', models.TextField(blank=True, default='', verbose_name='نص الحكم')),
                ('judgment_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحكم')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='accounts.case', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'حكم القضية',
                'verbose_name_plural': 'أحكام القضايا',
            },
        ),
        migrations.CreateModel(
            name='CaseTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('registered', 'التسجيل'), ('case_submitted', 'رفع القضية'), ('sessions', 'الجلسات'), ('judgment', 'الحكم'), ('appeal', 'استئناف'), ('closed', 'إغلاق')], max_length=30, verbose_name='المرحلة')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='accounts.case', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'مرحلة قضية',
                'verbose_name_plural': 'مراحل القضايا',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='text', max_length=50, verbose_name='المصدر')),
                ('text', models.TextField(verbose_name='النص')),
                ('label', models.CharField(choices=[('positive', 'إيجابي'), ('neutral', 'محايد'), ('negative', 'سلبي')], default='neutral', max_length=20, verbose_name='التصنيف')),
                ('score', models.IntegerField(default=0, verbose_name='الدرجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentiments', to='accounts.case', verbose_name='القضية')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentiments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تحليل مشاعر',
                'verbose_name_plural': 'تحليلات المشاعر',
                'ordering': ['-created_at'],
            },
        ),
    ]
