# Generated by Django 6.0 on 2026-01-05 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auditevent_caseoutcome_casetimelineevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseoutcome',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casetimelineevent',
            name='case',
        ),
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='case',
        ),
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='user',
        ),
        migrations.CreateModel(
            name='AccountTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('registered', 'تسجيل حساب'), ('profile_updated', 'تحديث ملف'), ('case_created', 'رفع قضية'), ('agreement_signed', 'توقيع/موافقة اتفاقية'), ('payment_submitted', 'رفع إيصال دفع'), ('status_changed', 'تغيير حالة')], max_length=30, verbose_name='الإجراء')),
                ('ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='مرجع')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_trails', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مسار المستخدم',
                'verbose_name_plural': 'مسارات المستخدم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'تسجيل دخول ناجح'), ('login_failed', 'محاولة دخول فاشلة'), ('logout', 'تسجيل خروج'), ('input_rejected', 'إدخال مرفوض'), ('access_denied', 'منع وصول'), ('case_created', 'إنشاء قضية'), ('payment_submitted', 'رفع إيصال دفع'), ('master_action', 'إجراء بالماستر')], max_length=30, verbose_name='نوع الحدث')),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True, verbose_name='IP')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='المسار')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حدث أمني',
                'verbose_name_plural': 'الأحداث الأمنية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AuditEvent',
        ),
        migrations.DeleteModel(
            name='CaseOutcome',
        ),
        migrations.DeleteModel(
            name='CaseTimelineEvent',
        ),
        migrations.DeleteModel(
            name='SentimentAnalysis',
        ),
    ]
