# Generated by Django 6.0 on 2026-01-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_caseoutcome_case_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityevent',
            name='user',
        ),
        migrations.AddField(
            model_name='useragreement',
            name='token_bound_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ربط التوكن'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='token_bound_session_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='هاش جلسة الربط'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='token_bound_user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent عند الربط'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء رابط الاتفاقية'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='token_last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر IP استخدم التوكن'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='token_revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إبطال التوكن'),
        ),
        migrations.DeleteModel(
            name='AccountTrail',
        ),
        migrations.DeleteModel(
            name='SecurityEvent',
        ),
    ]
