# Generated by Django 6.0 on 2026-01-05 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_securityevent_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useragreement',
            name='token_bound_at',
        ),
        migrations.RemoveField(
            model_name='useragreement',
            name='token_bound_session_hash',
        ),
        migrations.RemoveField(
            model_name='useragreement',
            name='token_bound_user_agent',
        ),
        migrations.RemoveField(
            model_name='useragreement',
            name='token_expires_at',
        ),
        migrations.RemoveField(
            model_name='useragreement',
            name='token_last_ip',
        ),
        migrations.RemoveField(
            model_name='useragreement',
            name='token_revoked_at',
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('auth_login', 'دخول'), ('auth_logout', 'خروج'), ('auth_failed', 'محاولة دخول فاشلة'), ('profile_update', 'تحديث الملف الشخصي'), ('case_create', 'رفع قضية'), ('agreement_accept', 'موافقة اتفاقية'), ('agreement_sign', 'توقيع اتفاقية'), ('payment_submit', 'إرسال إيصال دفع'), ('master_message', 'رسالة ماستر'), ('security_block', 'حظر أمني'), ('view', 'تصفح صفحة')], max_length=40, verbose_name='نوع الحدث')),
                ('path', models.CharField(blank=True, max_length=300, null=True, verbose_name='المسار')),
                ('ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, null=True, verbose_name='User-Agent')),
                ('meta', models.TextField(blank=True, null=True, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحدث')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل أمني',
                'verbose_name_plural': 'السجلات الأمنية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('registered', 'التسجيل'), ('case_submitted', 'رفع القضية'), ('under_review', 'مراجعة المكتب'), ('sessions', 'الجلسات'), ('judgment', 'الحكم'), ('appeal', 'استئناف'), ('closed', 'إغلاق')], max_length=30, verbose_name='المرحلة')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الحدث')),
                ('description', models.TextField(blank=True, null=True, verbose_name='تفاصيل')),
                ('outcome', models.CharField(choices=[('win', 'كسب القضية'), ('lose', 'خسارة'), ('appeal', 'استئناف'), ('pending', 'قيد المتابعة')], default='pending', max_length=20, verbose_name='النتيجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='accounts.case', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'تسلسل قضية',
                'verbose_name_plural': 'تسلسل القضايا',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('client', 'العميل'), ('lawyer', 'المحامي')], max_length=10, verbose_name='المستهدف')),
                ('label', models.CharField(choices=[('positive', 'إيجابي'), ('neutral', 'محايد'), ('negative', 'سلبي')], max_length=10, verbose_name='التصنيف')),
                ('score', models.IntegerField(default=0, verbose_name='الدرجة')),
                ('source_text', models.TextField(blank=True, null=True, verbose_name='النص المحلل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التحليل')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentiments', to='accounts.case', verbose_name='القضية')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentiments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تحليل مشاعر',
                'verbose_name_plural': 'تحليلات المشاعر',
                'ordering': ['-created_at'],
            },
        ),
    ]
