# Generated by Django 6.0 on 2025-12-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'موعد', 'verbose_name_plural': 'المواعيد'},
        ),
    ]
