# Generated by Django 6.0 on 2025-12-20 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_appointment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='رقم القضية')),
                ('case_type', models.CharField(choices=[('civil', 'قضية مدنية'), ('commercial', 'قضية تجارية'), ('family', 'أحوال شخصية'), ('criminal', 'قضية جنائية'), ('other', 'أخرى')], max_length=20, verbose_name='نوع القضية')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان القضية')),
                ('description', models.TextField(verbose_name='تفاصيل القضية')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='cases/', verbose_name='مرفقات')),
                ('status', models.CharField(default='جديدة', max_length=30, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'قضية',
                'verbose_name_plural': 'القضايا',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
